### ISSUE TITLE
Cursor goes to wrong position when deleting a digit

### ISSUE THREAD

**Issue by botura** [jonathanpmartins/v-money3#18]
I found two cases where cursor goes to wrong position after a digit has been deleted.

Just use the [codesandbox example](https://codesandbox.io/s/v-money3-use-as-component-oqdc6?file=/src/App.vue)

Case 1:
a) type 123456 (R$ 1.234,56)
b) delete digit 1. Cursor will be positioned between digits 2 and 3

Case 2:
a) type 1234567890 (R$ 12.345.678,90)
b) delete digit 1. Cursor will be positioned between digits 2 and 3

Thanks for you work on this component!

**Comment by jonathanpmartins** [comment]
Thanks for reporting the issue!

This problem is present in the old v-money repository and was carried in with the upgrade to vue3. It was introduced in this commit: https://github.com/vuejs-tips/v-money/commit/7435abb15ef973769f3232bda14f5296383f9d86

@botura problem fixed in the last v-money3 (3.13.7) release.
