### ISSUE TITLE
when allowBlank is set last digits are missing

### ISSUE THREAD

**Issue by mazraara** [jonathanpmartins/v-money3#38]
when allowBlank is FALSE

€30.00
10.00%

![image](https://user-images.githubusercontent.com/2024844/130058941-89111d9f-2d85-4608-a9dc-fba44e364936.png)

allowBlank is TRUE

€0.30
0.10%

![image](https://user-images.githubusercontent.com/2024844/130059273-4c24d32f-8100-4b66-a41f-aa7ddd077cad.png)

![image](https://user-images.githubusercontent.com/2024844/130059422-87e7581e-f7c3-4c0d-bf95-8cba2681d50b.png)

below is my overall config 

`{ "decimal": ".", "thousands": ",", "prefix": "€", "suffix": "", "min": 0, "max": 1000000, "precision": 2, "masked": false, "allowBlank": true, "disableNegative": true }
`

**Comment by mazraara** [comment]
i am using this as a directive, when i am using the component then this issue is no longer present

**Comment by jonathanpmartins** [comment]
I will take a look at it next week. I'm currently refactoring some of the original code and this issue is next on the list!
Thanks for reporting!

**Comment by jonathanpmartins** [comment]
The code-base has suffered a big refactoring. Some behavior has become default with `v-model`. Please read the news on the [docs](https://github.com/jonathanpmartins/v-money3/blob/main/README.md) page. 

Directives are capable to work with `Arbitrary Precision` but in exchange it cannot work with floats by default anymore. Directives use `v-model`...

Using `v-model` with precision `2`:
- If you setup `1` it will interpret it as `0.01`.
- If you setup `10` or `1.0` it will interpret it as `0.10`.
- If you setup `100` or `10.0` it will interpret it as `1.00`.
- If you setup `1.00` it will interpret it as `1.00`.
- If you setup `10.00` it will interpret it as `10.00`.
- If you setup `100.00` it will interpret it as `100.00`.

The components allow you to work with numbers with the `v-model.number` modifier.

Using `v-model.number` with precision `2`:
- If you setup `1` it will interpret it as `1.00`.
- If you setup `10` or `1.0` it will interpret it as `10.00`.
- If you setup `100` or `10.0` it will interpret it as `100.00`.
- If you setup `1.0` it will interpret it as `1.00`.
- If you setup `10.0` it will interpret it as `10.00`.
- If you setup `100.0` it will interpret it as `100.00`.

I really encourage you to use the component instead of the directive, or change your format value when setup.

But...

If you really want to work with directives you can configure it manually.

This sould work on the new release of `v-money3`.
```html
<input :model-modifiers="{ number: true }" v-model.lazy="amount" v-money3="config" />
```
